import Navigation from './components/Navigation'
import '../styles/globals.css'
import Link from 'next/link'
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
//ENVUELVE RUTAS EN UN COMPONENTE LAYOUT
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* TODO EL TEMA DE SEO VA AQUI */}
      <title>My app NExtjs</title>
      {/* AQUI VA TODO LO DEL BODY */}
      <body>
       <Navigation />
        {/* AQUI SE CARGAN TODAS LAS RUTAS, ARCHIVOS, ETC DE LA APP PARA MOSTRARSE  */}
        {children}
      </body>
    </html>
  )
}